Homework 1
ok-technopolis-2020/Gulyaev_Anton pull request #1
Opened 2020-10-09 18:04 UTC by kish-dev

2020-10-12 09:35 UTC, fromanywhere requested changes

2020-10-12 09:35 UTC, fromanywhere commented on Form.html
> +                    </label> <Br>
br здесь и далее не нужен

2020-10-12 09:35 UTC, fromanywhere commented on Form.html
> +    <label class="info-items">2 items left</label>
label ни к чему не привязан, лучше div или span

2020-10-12 09:35 UTC, fromanywhere commented on Form.html
> +    </div>
Кнопка удаления всего потерялась

2020-10-12 09:35 UTC, fromanywhere commented on Form.html
> +                    <button aria-label="Button to add todo">Add Todo</button>
форматирование поползло

2020-10-15 20:29 UTC, kish-dev commented on Form.html
> +                    </label> <Br>
@fromanywhere Удалил <Br>

2020-10-15 20:34 UTC, kish-dev commented on Form.html
> +    </div>
Добавил кнопку удаления всего задачек @fromanywhere

2020-10-16 12:40 UTC, fromanywhere approved these changes

2020-11-02 22:29 UTC, merged